language: php

php:
  - 7.2
  - 7.1

sudo: false

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - composer dump-autoload

script: ./vendor/bin/phpunit
